import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { useSession } from "next-auth/react";

export default function Layout({ children, title, user }) {
  const { status, data: session } = useSession();
 
  return (
    <>
      <Head>
        <title>{title ? title + " - VOOK" : "VOOK"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="flex min-h-screen flex-col justify-between items-center">
        <Navbar session={session} status={status} user={user} />
        <main className="m-auto mt-4 lg:px-4 flex flex-col items-center">
          {children}
        </main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright © 2022 VOOK</p>
        </footer>
      </div>
    </>
  );
};