import React from "react";
import Head from "next/head";
import ProfileNavigation from "../components/ProfileNavigation";
import { useSession } from "next-auth/react";

export default function ProfileLayout({title, children, user, image}) {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>{title ? title + " - VOOK" : "VOOK"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="flex max-h-screen flex-col justify-between items-center">
        <ProfileNavigation session={session} user={user} image={image} />
        <main className="container md:w-[85%] h-full m-auto lg:px-4 relative">{children}</main>
      </div>
    </>
  );
}

